#include <drivers/hikey_tzpc.h>
#include <io.h>
#include <trace.h>

#define SOC_TZPC_BASE_ADDR 0xF8002000
/* offset address */
#define SOC_TZPC_TZPCDECPROT0STAT_ADDR 0x0800
#define SOC_TZPC_TZPCDECPROT0SET_ADDR 0x0804

#define SOC_TZPC_TZPCDECPROT1STAT_ADDR 0x080C
#define SOC_TZPC_TZPCDECPROT1SET_ADDR 0x0810

/* #define SOC_TZPC_TZPCDECPROT2STAT_ADDR 0x0818 */
/* #define SOC_TZPC_TZPCDECPROT2SET_ADDR 0x081C  */

#define SOC_TZPC_TZPCDECPROT3STAT_ADDR 0x0824
#define SOC_TZPC_TZPCDECPROT3SET_ADDR 0x0828

#define AO_SC_PERIPH_CLKEN4	0x630
#define AO_SC_PERIPH_CLKSTAT4	0x638

#define PERI_SC_PERIPH_CLKEN3	0x230
#define PERI_SC_PERIPH_CLKSTAT3	0x238

/* register flag */
#define AO_SC_PERIPH_CLKEN4_PCLK_TZPC   (1 << 11)
#define PERI_CLK3_TZPC_DEP		(1 << 21)

/* base:       AO_CTRL_BASE			*/
/* tzpc_clk:   AO_SC_PERIPH_CLKEN4_PCLK_TZPC 	*/
/* stat_reg:   AO_SC_PERIPH_CLKSTAT4		*/

void tzpc_init(vaddr_t base)
{
	unsigned int data;
	/* enable TZPC */
	
	write32(AO_SC_PERIPH_CLKEN4_PCLK_TZPC,base+AO_SC_PERIPH_CLKEN4);
	do {
		data = read32(base+AO_SC_PERIPH_CLKSTAT4);

	} while (!(data & AO_SC_PERIPH_CLKEN4_PCLK_TZPC));

	/*
	EMSG("TZPCstat0: 0x%x\n",read32(SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT0STAT_ADDR));	
	write32(0xFFFFFFFF,SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT0SET_ADDR);
	do {
		data = read32(SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT0STAT_ADDR);

	} while (!(data & 0xFFFFFFFF));
	EMSG("TZPCstat0: 0x%x\n",read32(SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT0STAT_ADDR));	
	*/
	/*
	EMSG("TZPCstat1: 0x%x\n",read32(SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT1STAT_ADDR));	
	write32(0x3FFFFFFF,SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT1SET_ADDR);
	do {
		data = read32(SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT1STAT_ADDR);

	} while (!(data & 0x3FFFFFFF));
	EMSG("TZPCstat1: 0x%x\n",read32(SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT1STAT_ADDR));	
	*/
	/*
	EMSG("TZPCstat2: 0x%x\n",read32(SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT2STAT_ADDR));	
	write32(0x00000000,SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT2SET_ADDR);
	do {
		data = read32(SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT2STAT_ADDR);

	} while (!(data & 0x00000000));
	EMSG("TZPCstat2: 0x%x\n",read32(SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT2STAT_ADDR));	
	*/
	EMSG("TZPCstat3: 0x%x\n",read32(SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT3STAT_ADDR));	
	write32(0x0BFFFFFF,SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT3SET_ADDR);
	do {
		data = read32(SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT3STAT_ADDR);

	} while (!(data & 0x0BFFFFFF));
	EMSG("TZPCstat3: 0x%x\n",read32(SOC_TZPC_BASE_ADDR+SOC_TZPC_TZPCDECPROT3STAT_ADDR));	

}


/* base: 	 PERI_BASE			*/
/* tzpc_dep_clk: PERI_CLK3_TZPC_DEP		*/
/* stat_reg: 	 PERI_SC_PERIPH_CLKSTAT3	*/

void tzpcdep_init(vaddr_t base)
{
	unsigned int data;
	/* enable tzpc_dep */
	write32(PERI_CLK3_TZPC_DEP,base+PERI_SC_PERIPH_CLKEN3);
	do {
		data = read32(base+PERI_SC_PERIPH_CLKSTAT3);
	} while (!(data & PERI_CLK3_TZPC_DEP));
}
